version: "3.7"

services:

  app:
    build: ./app
    container_name: Application Flask IA-Racing
    restart: always
    environment:
      - APP_NAME=IA-Racing
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"